# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dummies.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(250, 200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.grid_cw = QtWidgets.QGridLayout()
        self.grid_cw.setObjectName("grid_cw")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 228, 178))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.grid_scroll = QtWidgets.QGridLayout()
        self.grid_scroll.setObjectName("grid_scroll")
        self.label_gui = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_gui.setMaximumSize(QtCore.QSize(100, 30))
        self.label_gui.setObjectName("label_gui")
        self.grid_scroll.addWidget(self.label_gui, 1, 0, 1, 1)
        self.label_roscore = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_roscore.setMaximumSize(QtCore.QSize(100, 30))
        self.label_roscore.setObjectName("label_roscore")
        self.grid_scroll.addWidget(self.label_roscore, 0, 0, 1, 1)
        self.button_gui = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.button_gui.setMaximumSize(QtCore.QSize(100, 30))
        self.button_gui.setObjectName("button_gui")
        self.grid_scroll.addWidget(self.button_gui, 1, 1, 1, 1)
        self.button_roscore = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.button_roscore.setMaximumSize(QtCore.QSize(100, 30))
        self.button_roscore.setObjectName("button_roscore")
        self.grid_scroll.addWidget(self.button_roscore, 0, 1, 1, 1)
        self.label_slam = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_slam.setMaximumSize(QtCore.QSize(100, 30))
        self.label_slam.setObjectName("label_slam")
        self.grid_scroll.addWidget(self.label_slam, 2, 0, 1, 1)
        self.button_slam = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.button_slam.setMaximumSize(QtCore.QSize(100, 30))
        self.button_slam.setObjectName("button_slam")
        self.grid_scroll.addWidget(self.button_slam, 2, 1, 1, 1)
        self.label_close = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_close.setMaximumSize(QtCore.QSize(100, 30))
        self.label_close.setObjectName("label_close")
        self.grid_scroll.addWidget(self.label_close, 3, 0, 1, 1)
        self.button_close = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.button_close.setMaximumSize(QtCore.QSize(100, 30))
        self.button_close.setObjectName("button_close")
        self.grid_scroll.addWidget(self.button_close, 3, 1, 1, 1)
        self.gridLayout_5.addLayout(self.grid_scroll, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.grid_cw.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.grid_cw, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_gui.setText(_translate("MainWindow", "GUI:"))
        self.label_roscore.setText(_translate("MainWindow", "ROSCORE:"))
        self.button_gui.setText(_translate("MainWindow", "Init"))
        self.button_roscore.setText(_translate("MainWindow", "Init"))
        self.label_slam.setText(_translate("MainWindow", "SLAM:"))
        self.button_slam.setText(_translate("MainWindow", "Init"))
        self.label_close.setText(_translate("MainWindow", "Close all:"))
        self.button_close.setText(_translate("MainWindow", "Close"))
